packages:
  - 'api'
  - 'cli'
  - 'web'
allowBuilds:
  better-sqlite3: true
  core-js-pure: false
  dtrace-provider: false
  esbuild: true
  msw: true
  re2: true
minimumReleaseAge: 10080
minimumReleaseAgeStrict: true
engineStrict: true
