name: Setup node env
description: Setup pnpm, Node, install dependencies
inputs:
  registry-url:
    description: 'Registry URL to configure for publishing (optional)'
    required: false
    default: ''
  scope:
    description: 'Scope to associate with the registry (optional)'
    required: false
    default: ''
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4

    - uses: actions/setup-node@v6
      with:
        node-version-file: 'package.json'
        cache: 'pnpm'
        registry-url: ${{ inputs.registry-url }}
        scope: ${{ inputs.scope }}

    - run: pnpm install --frozen-lockfile
      shell: bash
