name: Setup node env
description: Enable corepack, setup Node, install dependencies
runs:
  using: composite
  steps:
    # Makes the pnpm version used inside package.json the single source of truth
    - run: corepack enable
      shell: bash
    - run: corepack prepare --activate
      shell: bash

    - uses: actions/setup-node@v6
      with:
        node-version-file: 'package.json'
        cache: 'pnpm'

    - run: pnpm install --frozen-lockfile
      shell: bash
