name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  workflow_dispatch:

jobs:
  static-checks-md:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-node-env
      - name: Lint markdown
        run: pnpm lint:md

  static-checks-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-node-env
      - name: Lint api
        run: pnpm --filter api lint

      - name: Typecheck api
        run: pnpm --filter api typecheck

  static-checks-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-node-env
      - name: Lint cli
        run: pnpm --filter ./cli lint

      - name: Typecheck cli
        run: pnpm --filter ./cli typecheck

  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-node-env
      - name: Test api
        run: pnpm --filter api test
        env:
          DATABASE_PATH: /tmp/test.db

  test-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-node-env
      - name: Test cli
        run: pnpm --filter ./cli test

  deploy-staging:
    needs: [static-checks-md, static-checks-api, static-checks-cli, test-api, test-cli]
    if: contains(github.event.pull_request.labels.*.name, 'deploy-staging')
    uses: ./.github/workflows/deploy-staging.yml
    secrets: inherit
